### PR TITLE
RakeshR - Image Comments Challenge (Using Xcode12.1)

### PR DESCRIPTION
**Pull request by RakeshRiOS**
Hi Caio/Mike Please review this PR and provide your feedback.

Thanks,
Rakesh

### CODE REVIEW

**Comment by caiozullo** [comment]
Hi @RakeshRiOS,

The CI job is failing. This PR base branch is set to `xcode12` but looks like you started from or merged the `xcode12_2` branch into it. 

So you'll have to rebase to the `xcode12` branch removing the commits from xcode12_2`. Or update your solution to work with Xcode 12.2 (and update the PR base to xcode12_2).

**Comment by RakeshRiOS** [comment]
> Hi @RakeshRiOS,
> 
> The CI job is failing. This PR base branch is set to `xcode12` but looks like you started from or merged the `xcode12_2` branch into it.
> 
> So you'll have to rebase to the `xcode12` branch removing the commits from `xcode12_2`. Or update your solution to work with Xcode 12.2 (and update the PR base to xcode12_2).

Yes, i started with master branch and in the mid i switched to xcode12 branch. I'm trying to solve this issue.

**Comment by RakeshRiOS** [comment]
> > Hi @RakeshRiOS,
> > The CI job is failing. This PR base branch is set to `xcode12` but looks like you started from or merged the `xcode12_2` branch into it.
> > So you'll have to rebase to the `xcode12` branch removing the commits from `xcode12_2`. Or update your solution to work with Xcode 12.2 (and update the PR base to xcode12_2).
> 
> Yes, i started with master branch and in the mid i switched to xcode12 branch. I'm trying to solve this issue.

Hi Caio, I tried creating new branch from the fresh and tried to create a PR but facing the same issue. Do i need to start from the beginning by forking from different Github account?

**Comment by caiozullo** [comment]
Hi @RakeshRiOS, there are many ways to fix it. If you're not confident rebasing, you could create a new branch from `xcode12` and cherry-pick only your commits into it.

For example:

```
git checkout xcode12
git pull origin xcode12
git checkout -b your-new-branch-name
git cherry-pick cfeb1e9^..1d816da
```

Then, you can create a new PR or force push the changes into the branch you used in this PR.

**Comment by caiozullo** [comment]
Make sure to remove this merge commit which mixed up the branches: https://github.com/essentialdevelopercom/ios-lead-essentials-image-comments-challenge/pull/5/commits/165cd8b6116eccf36e430779f2ca4d1b68862037

**Comment by RakeshRiOS** [comment]
> Hi @RakeshRiOS, there are many ways to fix it. If you're not confident rebasing, you could create a new branch from `xcode12` and cherry-pick only your commits into it.
> 
> For example:
> 
> ```
> git checkout xcode12
> git pull origin xcode12
> git checkout -b your-new-branch-name
> git cherry-pick cfeb1e9^..1d816da
> ```
> 
> Then, you can create a new PR or force push the changes into the branch you used in this PR.

Ok. I did tried to follow these steps and ended up in same issue (https://github.com/essentialdevelopercom/ios-lead-essentials-image-comments-challenge/pull/9)
Not sure whats really messing up.

**Comment by caiozullo** [comment]
Hi @RakeshRiOS, the `xcode12` branch in your fork was also merged with `xcode12_2`.

So your fork has a different history than the main repository. You can create a new branch from the last commit of the correct `xcode12` branch (729d3a766cff17bcc91113f56a28d53de2d838be).

Then, you can cherry-pick your changes without the merge commit which mixed up the branches (165cd8b).

For example:

```
git checkout 729d3a766cff17bcc91113f56a28d53de2d838be

git checkout -b your-new-branch-name

git cherry-pick cfeb1e9^..c11ef10

git cherry-pick eaa0f58^..1d816da
```

You'll probably have to solve some merge conflicts as you cherry-pick the commits because the history is mixed up.

*P.S. I highly recommend you invest time mastering `git`, it's an essential skill for developers - it'll make you much more productive.*

**Comment by RakeshRiOS** [comment]
> Hi @RakeshRiOS, the `xcode12` branch in your fork was also merged with `xcode12_2`.
> 
> So your fork has a different history than the main repository. You can create a new branch from the last commit of the correct `xcode12` branch ([729d3a7](https://github.com/essentialdevelopercom/ios-lead-essentials-image-comments-challenge/commit/729d3a766cff17bcc91113f56a28d53de2d838be)).
> 
> Then, you can cherry-pick your changes without the merge commit which mixed up the branches ([165cd8b](https://github.com/essentialdevelopercom/ios-lead-essentials-image-comments-challenge/commit/165cd8b6116eccf36e430779f2ca4d1b68862037)).
> 
> For example:
> 
> ```
> git checkout 729d3a766cff17bcc91113f56a28d53de2d838be
> 
> git checkout -b your-new-branch-name
> 
> git cherry-pick cfeb1e9^..c11ef10
> 
> git cherry-pick eaa0f58^..1d816da
> ```
> 
> You'll probably have to solve some merge conflicts as you cherry-pick the commits because the history is mixed up.
> 
> _P.S. I highly recommend you invest time mastering `git`, it's an essential skill for developers - it'll make you much more productive._

Yes, i was making mistake while creating the new branch. Thanks for pointing it out Caio. I have created a new branch with new PR please provide your feedback.

**Comment by RakeshRiOS** [comment]
Closing this PR now.

**Pull request closed without merging**
